# Generated by Django 5.0.1 on 2024-03-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='rate',
        ),
    ]
