# Generated by Django 5.0.1 on 2024-03-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_quantity', models.IntegerField()),
                ('total_value', models.IntegerField()),
            ],
        ),
    ]
