# Generated by Django 5.0.1 on 2024-03-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pending',
            field=models.IntegerField(default=0),
        ),
    ]
