# Generated by Django 5.0.1 on 2024-03-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='pending',
            new_name='payment',
        ),
    ]
