# Generated by Django 5.0.1 on 2024-03-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_rename_pending_invoice_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total_value',
            new_name='gross_value',
        ),
    ]
