# Generated by Django 5.0.3 on 2024-03-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
