# Generated by Django 5.0.1 on 2024-03-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
